### ISSUE TITLE
Not compatible with PhpStorm 2018.1 EAP

### ISSUE THREAD

**Issue by mix359** [Haehnchen/idea-php-annotation-plugin#108] opened 2018-02-19 10:30 UTC
I've updated to the last EAP version of PhpStorm 2018.1 EAP (Build #PS-181.3741.23, built on February 14, 2018) and it says that "the plugin PHP Annotation is not compatible with this build of the IDE".

I've tried to uninstall the plugin and not is not showed in the plugin list and I couldn't reinstall it.

The symfony plugin seam to be compatible, but couldn't be loaded because of the dependency with this plugin that could not be solved. 

Thanks for the work you're making!
Cheers
Mix

**Comment by rdohms** [comment] 2018-02-19 10:48
Duplicate of #105, solved by #107, all we need is a build/tag to test.

**Comment by mix359** [comment] 2018-02-19 11:15
Thanks,

Sorry, I haven't seen the Closed issue about this.
It's not working at the moment and there wasn't any new release, so it's strange that there isn't any open issue because is still not solved o.o

I'll wait for the build :)

**Comment by Haehnchen** [comment] 2018-02-19 16:55
... build shipping

**Comment by Catalin-Ionut** [comment] 2018-03-30 07:53
Phpstorm 2018.1 officially released, can this be updated so it works as a dependency to symfony plugin?

**Comment by Emulator000** [comment] 2018-03-30 09:04
Same here, please update the Plugin, thank you!

**Comment by Catalin-Ionut** [comment] 2018-03-30 10:18
@anuri73 Correct, after reinstalling everything works fine. Thanks a bunch.

**Comment by dagomar** [comment] 2018-03-30 11:14
I didn't need to reinstall, but I did need to update the plugin manually. I noticed that when in settings > plugins, the update button doesn't show until you click 'Browse repositories'. Hope this saves a couple of seconds :-)

**Comment by King2500** [comment] 2018-03-30 13:14
I used "Check for Update" and after Annotations plugin was updated Symfony plugin worked again.

**Comment by TomAdam** [comment] 2018-03-31 14:30
I for one am glad this was here. The readme doesn't explicitly indicate compatibility with 2018.1, in fact the matched release versions appear to indicate it is not yet supported. This agreed with the error PHPStorm gave. Perhaps add a note to the readme before closing this ticket?

**Comment by chx** [comment] 2018-04-01 02:53
Yeah this plugin became incredibly important, now it seems like half the world depends on it. Half my world, anyways :)

**Comment by drugan** [comment] 2018-04-01 15:56
I've fixed this issue by right clicking on the `PHP Annotations` entry and then `Reload List of Plugins` option. After that the `Uninstall` button turned into the `Update` one. After updating the plugin the warning has disappeared.
![reload-plugins](https://user-images.githubusercontent.com/3609840/38174990-5b3b0f52-35de-11e8-82dc-fea7d62c6907.png)

**Comment by chx** [comment] 2018-04-01 21:28
Is this a phpstorm bug then? Instead of disabling it outright shouldn't it offer to update it...?

**Comment by pppdns** [comment] 2018-04-05 20:43
Just tried it, auto update suggested this update for me when PHPStorm started (2018.1.1 EAP), I didn't have to manually update it from the plugin list or reinstall anything

**Comment by cedricziel** [comment] 2018-10-04 11:21
Closing as this seems to be resolved.

**Closed by cedricziel** 2018-10-04 11:21 UTC

**Comment by soopermouse** [comment] 2019-01-15 20:21
not resolved, this is still happening
