### ISSUE TITLE
Compatible with PHP Storm 2018.1 (Release) BUT Automatic Update Not Triggering

### ISSUE THREAD

**Issue by lloy0076** [Haehnchen/idea-php-annotation-plugin#115] opened 2018-04-03 10:56 UTC
### Plugin Version

5.21

### PHP Storm Version

2018.1

```
PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
[removed - privacy]
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

### Error

```
2018-04-03
6:51 AM	Plugin Error
Problems found loading plugins:
  Plugin "Symfony Plugin" was not loaded: required plugin "PHP Annotations" not installed.
  Disable Symfony Plugin
  Enable PHP Annotations
  Open plugin manager

The following plugins are incompatible with the current IDE build: PHP Annotations
```

Note especially, the last line.

### Other Comments
It could be said this is a duplicated of #105 but this is more important because this **is** the paid release.

Possibly fixed by #107?

**Comment by lloy0076** [comment] 2018-04-03 10:57
2018-04-03
6:51 AM	Plugin Error
				Problems found loading plugins:
				Plugin "Symfony Plugin" was not loaded: required plugin "PHP Annotations" not installed.
				Disable Symfony Plugin
				Enable PHP Annotations
				Open plugin manager
				The following plugins are incompatible with the current IDE build: PHP Annotations

**Comment by lisachenko** [comment] 2018-04-04 08:13
Looks like many plugins are affected by this issue, @Haehnchen could you make a new release with fix for that?

**Comment by vikbert** [comment] 2018-04-04 09:01
has the same problem in the same version as @lloy0076

**Comment by lisachenko** [comment] 2018-04-04 09:55
Looks like version 5.3 is already available, but it doesn't appear as automatic update available. You need go to "Settings -> Plugins -> Browse repositories", then type "PHP Annotations" and press `Update` button on the right panel.
After restart, everything should work. Confirmed for 2018.1

**Comment by fridde** [comment] 2018-04-05 08:58
The manual update described by @lisachenko worked for me,
Maybe we should rewrite the issue as some kind of "PHP Annotations does not automatically appear as available update".
@lloy0076 , you might be able to do that?

**Comment by MatthiasKuehneEllerhold** [comment] 2018-04-05 09:37
Clicking on PHPStorm -> Check for Updates suggested this update. Am I alone with this?

**Comment by lloy0076** [comment] 2018-04-05 10:52
So this **is** compatible if one forces an update now...it's still some sort of issue.

**Comment by pppdns** [comment] 2018-04-05 20:40
Auto update suggested this update for me when PHPStorm started (2018.1.1 EAP), I didn't have to manually update it from the plugin list, seems like this issue can be closed

**Comment by frak** [comment] 2018-04-09 10:17
I just updated to 2018.1 and had to find this issue and manually update PHP Annotations

**Comment by Metabor** [comment] 2018-04-09 14:12
Same problem as frak, but I noticed that "Automatically check updates for ..." checkbox is not checked anymore after updating to 2018.1 I guess if this would have been checked it would have ben updated automatically (as it was in the version before for me).
So problem seems not be related to this plug-in.

**Comment by pculka** [comment] 2018-04-19 11:11
Ditto. Needed to google up this issue first, now it works

**Comment by cedricziel** [comment] 2018-10-04 11:46
Closing as it's not related.

**Closed by cedricziel** 2018-10-04 11:46 UTC
