### ISSUE TITLE
Issue #44 returned

### ISSUE THREAD

**Issue by ABM-Dan** [Haehnchen/idea-php-annotation-plugin#76] opened 2016-12-09 16:27 UTC
Opening this because I don't know how to reopen #44, all the relevant info is there.

**Comment by dbiagi** [comment] 2016-12-09 18:52
Just discovered this issue. After reformat code, my app was broken.

**Comment by JKetelaar** [comment] 2016-12-09 23:32
Same here

**Comment by avramcosmin** [comment] 2016-12-10 00:37
Same here with `use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity` and a bunch of many other imports after installing PhpStorm 2016.3.1.

**Comment by dorcyv** [comment] 2016-12-11 18:46
I think [this issue](https://youtrack.jetbrains.com/issue/WI-34285) is related

**Comment by Haehnchen** [comment] 2016-12-11 18:57
fine a self resolving issue for me :)

**Comment by acelaya** [comment] 2016-12-12 07:57
Same here. It happens with any kind of annotation.
As a temporary workaround, I have noticed that aliased annotations are not marked as unused.

In this case, the `Inject` annotation is marked as unsued:

```php
<?php
namespace App\Middleware;

use Acelaya\ZsmAnnotatedServices\Annotation\Inject;

class Foo
{
    /**
     * @Inject({Cache::class})
     */
    public function __construct(Cache $cache)
    {
        $this->cache = $cache;
    }
}
```

But not in this case:

```php
<?php
namespace App\Middleware;

use Acelaya\ZsmAnnotatedServices\Annotation as DI;

class Foo
{
    /**
     * @DI\Inject({Cache::class})
     */
    public function __construct(Cache $cache)
    {
        $this->cache = $cache;
    }
}
```

**Comment by luispabon** [comment] 2016-12-13 13:05
Can confirm this is also happening to me, on 2016.3.1 and latest plugin.

**Comment by rvanlaak** [comment] 2016-12-13 14:56
@Haehnchen you probably mean that it isn't due to the plugin, but to the PHPStorm API right? https://github.com/Haehnchen/idea-php-annotation-plugin/issues/76#issuecomment-266299990

**Comment by iltar** [comment] 2016-12-14 07:32
Same here, tried with any non-aliased annotation, but everything is detected as unused. This goes for SensioLabs Route, Template, Security; Symfony Route; Custom Annotations. I think it's really broken :(

**Comment by dorcyv** [comment] 2016-12-14 11:45
I can confirm that this issue is solved by this build:
CLion 2016.3.1
Build #CL-163.9166.31, built on December 13, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by iltar** [comment] 2016-12-14 11:59
I'm locally (EAP) running: `Build version: PhpStorm 2016.3.2 EAP Build #PS-163.10154.2 December 13, 2016` and I can confirm this is fixed.

**Comment by ABM-Dan** [comment] 2016-12-14 16:05
Thank you @iltar :)

**Comment by vudaltsov** [comment] 2016-12-15 20:32
For those (like me 10 minutes ago) who don't know [where to find EAP builds of PhpStorm](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program).

**Comment by lifo101** [comment] 2017-01-03 15:16
I commented on #44 by mistake. I just upgraded IntelliJ to `2016.3.2` and this bug started to occur. If I use my other computer that still has 2016.3 this is not an issue. Both computers are using PHP-Annotation plugin v4.2.

**Bugged:** 
```
IntelliJ IDEA 2016.3.2
Build #IU-163.10154.41, built on December 21, 2016
Licensed to ...
You have perpetual fallback license for this version
Subscription is active until November 29, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

**Works:** 
```
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
Licensed to ...
You have perpetual fallback license for this version
Subscription is active until November 29, 2017
JRE: 1.8.0_25-b18 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
```

**Comment by Haehnchen** [comment] 2017-01-10 18:12
fyi: `2016.3.2` is working as expected `2016.3.1` is now blacklisted: https://github.com/Haehnchen/idea-php-annotation-plugin/blob/master/.travis.yml#L22

**Closed** 2017-07-26 17:50 UTC
Labels: api, eap, fixed
