### ISSUE TITLE
Imported classes are marked as unused when used for constant

### ISSUE THREAD

**Issue by stefnoten** [Haehnchen/idea-php-annotation-plugin#51] opened 2016-03-09 21:32 UTC
When importing classes for using its constants in an annotation, the imports are incorrectly marked as unused. Example:

```php
namespace A;

use JMS\DiExtraBundle\Annotation as DI;
use Some\Namespace\To\MyEvents; // incorrectly marked as unused

class SomeClass {
    /** @DI\Observe(MyEvents::SOME_EVENT) */
    public function doSomething() {
    }
}
```

I'm using the latest version of the plugin (2.6.2). This makes it impossible to let the IDE automically optimize imports (e.g. via the shortcut or on commit). When not using this feature, it is still error-prone because mistakenly removing such an import will break the code.

**Comment by thebigb** [comment] 2016-03-22 19:32
Dupe of #18, #22 and #26?

Those issues have been silent for a while though.

**Comment by thebigb** [comment] 2016-04-08 09:01
@Haehnchen, I would be willing to take a look at this, but could you provide a few pointers on where to look?

Additionally do you have any tips for debugging an extension like this? I tried debugging this plugin some time ago to figure out how it works, but most breakpoints that I would set would not go off.

**Comment by acelayawonnova** [comment] 2016-04-16 11:09
@thebigb It is easy to reproduce. The doctrine/annotations package allows class constants to be passed to annotations, as in @stefnoten example, `@DI\Observe(MyEvents::SOME_EVENT)`, the `MyEvents::SOME_EVENT` constant is a valid param.
However, in order to get it working, the user statement with the FQCN needs to be present, `use Some\Namespace\To\MyEvents`, but PhpStorm marks it as unused, makeing it easy to be accidentally removed, for example by automatically optimizing the use statements.

I hope that helps you :-)

**Comment by danez** [comment] 2016-07-08 13:27
Can there anything be done about it? are there workarounds till this is fixed?

**Comment by Haehnchen** [comment] 2016-08-06 15:02
done

**Closed by Haehnchen** 2016-08-06 15:02 UTC
Labels: duplicate
