### ISSUE TITLE
PhpStorm 10: Unused symfony2 annotations imports

### ISSUE THREAD

**Issue by scaytrase** [Haehnchen/idea-php-annotation-plugin#44] opened 2015-11-02 18:04 UTC
Annotation imports became mark unused right after aftercompletion succeedes.

![image](https://cloud.githubusercontent.com/assets/6578413/10889805/277a8f02-81a5-11e5-8808-7eb86d16af2e.png)

PhpStorm 10.0
Build #PS-143.381, built on October 31, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

Plugin version: 2.6.1

**Comment by scaytrase** [comment] 2015-11-02 18:17
PhpStorm 9.0.2 with the same plugin version render imports OK

![image](https://cloud.githubusercontent.com/assets/6578413/10890101/23a5faa4-81a7-11e5-92f4-f7c83c332b41.png)

PhpStorm 9.0.2
Build #PS-141.2462, built on August 18, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

**Comment by lsv** [comment] 2015-11-03 00:42
Can confirm, just changed to PhpStorm 10 now.

If you remove the import line, then the annotation actually says it cant find the class

![screenshot from 2015-11-03 01 41 11](https://cloud.githubusercontent.com/assets/20708/10898574/1086efc6-81cc-11e5-9d95-a1ced802ef37.png)

**Comment by Haehnchen** [comment] 2015-11-03 20:29
I did a clean installation, its working fine.

@lsv that correct class is not imported so not known ;)
@scaytrase try a cache invalidation and rebuild it for new PhpStorm10 environment: "File > Invalidate Cache"

**Comment by scaytrase** [comment] 2015-11-04 07:44
`Invalidate Cache and Restart`, than reindexing did nothing. Any other ideas?

Reinstall plugin and reindex didn't help

**Comment by scaytrase** [comment] 2015-11-04 07:59
Hell, I've even dropped `.WebIde100` folder and reconfigured plugins. Same story. I've left only two custom plugins enabled - Symfony2 and PHP Annotations, rebuilt cache and restarted. Nothing changed.

**Comment by lsv** [comment] 2015-11-04 08:11
@Haehnchen ofcourse, it was just to show that the @Route actually looked for a class.

In symfony fullstack there are two different classes that gives you the route annotation.

```Symfony\Component\Routing\Annotation\Route``` and ```Sensio\Bundle\FrameworkExtraBundle\Configuration\Route``` if you choose the frameworkextra route annotation then it says the class is never used.

But if you use the component annotation then it works as before.

But it is not just the route annotation, the Method annotation which only is in the frameworkextra does not work at all.

(By "work" I mean it shows up as "class import never used", just in the first screenshot from OP)

**Comment by scaytrase** [comment] 2015-11-04 08:14
Yeah @lsv , Interesting note - component annotation marked as used correctly. At the same time FrameworkBundle one - not

![image](https://cloud.githubusercontent.com/assets/6578413/10932830/1dea7c68-82e5-11e5-837c-4818ff57eca1.png)

**Comment by lsv** [comment] 2015-11-04 08:21
The only difference I can see on the two classes are

The component route has the Target annotation, and the framework does not.

But again, both worked perfect in PHPStorm 9 (and still does) but not in 10 (so what have changed I dont know)

**Comment by jiahuanle** [comment] 2015-11-04 08:34
Can you share the phpStorm 10 license key？thank you

**Comment by iltar** [comment] 2015-11-11 11:29
It seems like the following annotations are not detected when used:
```php
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
```

The following work fine:
```php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Routing\Annotation\Route;
```

This is quite an issue for me as it would mean I remove used use statements.

**Comment by lsv** [comment] 2015-11-11 12:32
+1

**Comment by hoshsadiq** [comment] 2015-12-14 00:01
Any update on this?

**Comment by Haehnchen** [comment] 2015-12-14 07:42
yes. targets are missing in all classes https://github.com/sensiolabs/SensioFrameworkExtraBundle/tree/master/Configuration. but that should not break, will check that changes between PhpStorm 9 > 10 psi-struct/lexer

**Comment by desarrolla2** [comment] 2015-12-15 16:08
+1

**Comment by Haehnchen** [comment] 2016-01-31 17:10
can someone provide some project background. symfony version, ... ?. that ever i am trying all works as expected. :)

- try drop cache folder?
- multiple class names for eg Route?

**Comment by scaytrase** [comment] 2016-01-31 17:24
@Haehnchen currently I cannot reproduce this issue neither with PS10.0.3 nor with PS11 EAP (plugins are latest). Maybe something go fixed silently last two months. 

If some other confirm - then, issue should be gone.

**Comment by iltar** [comment] 2016-01-31 17:32
I think it has indeed been fixed in a patch in-between. I can verify tomorrow but I cannot remember running into this issue the past weeks.

**Comment by iltar** [comment] 2016-02-01 07:41
Update, I'm running 10.0.3 (jan 8) with annotations 2.6.2, and it's working here.

**Comment by fracasula** [comment] 2016-02-04 11:39
Same here with Ubuntu and PHPStorm 10.0.3. With me what's not working are other classes though so I don't think it's this plugin the culprit. PHPStorm says the ParamFetcher class that I'm using with type hinting is never used, plus a trait I wrote myself.

![import_never_used](https://cloud.githubusercontent.com/assets/1288256/12814037/ec762b2c-cb33-11e5-97f1-e297fca9e42f.png)

**Comment by hoshsadiq** [comment] 2016-02-04 11:48
@fracasula I think your issue is different. This plugin is to do with annotations, yours is a PhpStorm built in feature. You should raise this as an issue on YouTrack on Intellij's website.

**Comment by fracasula** [comment] 2016-02-04 11:55
@hoshsadiq That's why I wrote **_"so I don't think it's this plugin the culprit"_** in my previous comment. I was trying to point out that maybe this whole thing could probably be just about PHPStorm and not the plugin at all. Just saying though, so if you guys are sure about this then it makes sense you keep posting here.

**Comment by hackzilla** [comment] 2016-03-13 11:30
For future reference, this has been fixed by installing the PHP Annotations plugin.

https://youtrack.jetbrains.com/issue/WI-30512

**Comment by Haehnchen** [comment] 2016-03-13 18:26
so closed

**Closed by Haehnchen** 2016-03-13 18:26 UTC
Labels: question, wontfix

**Comment by plfort** [comment] 2016-06-03 09:41
I still have this issue with PHP Annotation 3.0.1 and PHPStorm 2016.1.2 (145.1616).
Cleaning index or reinstalling the plugin did not help.
Am i missing something ?

**Comment by denisvmedia** [comment] 2016-06-19 22:16
@Haehnchen 
I have this problem too, but in PhpStorm 10.0.4 and the plugin version 2.6.2. Tried clearing cache - no results. Tried re-installing it - no results. Shoudn't we re-open this issue?

**Comment by Haehnchen** [comment] 2016-06-20 17:53
not supporting version < 2016.x because of different api levels. versions +`2016.1` need also some updates because of #55

**Comment by Glideh** [comment] 2016-08-18 08:27
PhpStorm 2016.2 with Php Annotations 4.1.1 brings the annotation classes links but still shows false unused imports.

**Comment by vpArth** [comment] 2016-12-08 14:01
PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016

Same issue:

```
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
```

Both are `never used`

**Comment by vpArth** [comment] 2016-12-08 14:08
Workaround is aliasing:

```
use Sensio\Bundle\FrameworkExtraBundle\Configuration as C;

/**
 * @C\Route(...)
 * @C\Method()
 */

**Comment by shyinyong** [comment] 2016-12-16 05:59
You can install PHP Annotations plugin!

![image](https://cloud.githubusercontent.com/assets/8967995/21253223/c7e0157c-c397-11e6-90c0-352d6035c31b.png)

**Comment by lashae** [comment] 2016-12-16 06:14
It is already installed.

<img width="942" alt="screen shot 2016-12-16 at 09 12 52" src="https://cloud.githubusercontent.com/assets/20574/21253466/96662bc4-c367-11e6-8056-9dbcd93a53a1.png">
<img width="751" alt="screen shot 2016-12-16 at 09 13 29" src="https://cloud.githubusercontent.com/assets/20574/21253465/966427ca-c367-11e6-9de7-deebb029f3d8.png">

**Comment by lashae** [comment] 2016-12-16 06:22
It is already installed on the latest build of Phpstorm.

<img width="942" alt="screen shot 2016-12-16 at 09 12 52" src="https://cloud.githubusercontent.com/assets/20574/21253611/b1cdcbf0-c368-11e6-99e6-e2cfea948249.png">
<img width="751" alt="screen shot 2016-12-16 at 09 13 29" src="https://cloud.githubusercontent.com/assets/20574/21253612/b1cec604-c368-11e6-9066-d9063dfaf106.png">
<img width="639" alt="screen shot 2016-12-16 at 09 16 15" src="https://cloud.githubusercontent.com/assets/20574/21253613/b1d02f08-c368-11e6-990b-ac84f366ac10.png">

**Comment by iltar** [comment] 2016-12-16 08:47
It's fixed again in the latest EAP of phpstorm

**Comment by weph** [comment] 2016-12-20 10:58
Will this fix also be released for 2016.3.1?

**Comment by dramentol** [comment] 2016-12-21 09:35
I have the same problem.

PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016

PHP Annotations 4.2

**Comment by kugaudo** [comment] 2016-12-21 17:33
Actually @vpArth offered a nice workaround. Despite it's annoying it works fine.

You can automate inserting _use alias_ by using [PHP Annotations](https://plugins.jetbrains.com/plugin/7320) plugin:

![phpstorm_use_annotation](https://cloud.githubusercontent.com/assets/22676421/21399305/b909891e-c7b3-11e6-9a12-9b096ab24938.jpg)

Then you get:

![phpstorm_use_annotation_2](https://cloud.githubusercontent.com/assets/22676421/21399415/2bf62842-c7b4-11e6-9615-7eb61a3b7892.jpg)

PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016

PHP Annotations 4.2

**Comment by kugaudo** [comment] 2016-12-21 20:38
The last build of PhpStorm has a fix for the issue!

PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016

PHP Annotations 4.2

Voilà:

![phpstorm_use_annotation_fixed](https://cloud.githubusercontent.com/assets/22676421/21405287/ee9b2ef6-c7cd-11e6-893c-1bca58e393f5.jpg)

**Comment by lifo101** [comment] 2017-01-03 14:24
I just upgraded to 2016.3.2 and now these annotations are broken. I've tried invalidating/restarting/re-indexing/reinstalling the PHP annotations plugins, etc. And nothing seems to work. :(

```
IntelliJ IDEA 2016.3.2
Build #IU-163.10154.41, built on December 21, 2016
Licensed to ...
You have perpetual fallback license for this version
Subscription is active until November 29, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

![image](https://cloud.githubusercontent.com/assets/367337/21610425/ea70a1cc-d195-11e6-8ccc-d47c3ba38886.png)

**Comment by kugaudo** [comment] 2017-01-03 14:28
@lifo101 which version of PHP Annotations?

**Comment by lifo101** [comment] 2017-01-03 14:32
v4.2.


-- Jason

**Comment by dfreudenberger** [comment] 2017-01-03 22:30
same here, running php annotations v4.2 with intellij 2016.3.2

**Comment by mrfreitas** [comment] 2017-01-06 11:59
I can confirm that Intellij 2016.3.2 with php annotations v4.2 it's having this problem

**Comment by lifo101** [comment] 2017-01-06 12:20
Simple workaround (the aliasing suggestion someone made didn't work for me) is to simply reference the class of the unused imports:

```php
    protected function dummy()
    {
        // dummy code to fix bug in 'use' statements not being seen 
        // (IntelliJ v2016.3.2 + PHP Annotations v4.2)
        Route::class;
        Security::class;
    }
```
![image](https://cloud.githubusercontent.com/assets/367337/21717681/8ddf4c86-d3e0-11e6-84ba-6e59af2fd0df.png)

**Comment by dewos** [comment] 2017-01-10 15:31
@lifo101 you can use @see in annotation, it is more clean

/**
* @Route("/request")
*
* @see Route
*/
class FooController

**Comment by PhilETaylor** [comment] 2018-02-20 12:56
This is happening again :-( 

PHP Annotation Plugin 5.2.1 
PhpStorm 2018.1 EAP
Build #PS-181.3741.23, built on February 14, 2018
JRE: 1.8.0_152-release-1136-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by sawmurai** [comment] 2018-04-03 10:36
Happens in 2018.1

**Comment by scaytrase** [comment] 2018-04-03 10:52
in 2018.1 it happens because of plugin incompatibility. you should re-install (remove, restart, install) plugins in order get them back to life

**Comment by ddelrio1986** [comment] 2018-04-10 13:48
Recently upgraded PHPStorm and had to do exactly as @scaytrase described above to get warnings about "use Doctrine\ORM\Mapping as ORM;" imports not being used even though I was using it within docblock annotations. I just uninstalled the PHP Annotations plugin, restarted PHPStorm, installed the PHP Annotations plugin, then restarted PHPStorm again.
